version: '3.8'

services:
  # Oracle database for testing
  oracle-db:
    image: container-registry.oracle.com/database/free:23.4.0.0
    container_name: oracle-test-db
    environment:
      - ORACLE_PWD=${ORACLE_PWD:-TestPassword123}
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/${ORACLE_PWD:-TestPassword123}@localhost:1521/FREE", "as", "sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  tpcds-util:
    build:
      context: .
      dockerfile: Containerfile
    image: quay.io/tpcds/tpcds-util:latest
    container_name: tpcds-util
    
    # Wait for database to be ready
    depends_on:
      oracle-db:
        condition: service_healthy
    
    # Mount data directory for output
    volumes:
      - ./tpcds_data:/home/tpcds/tpcds_data
      - tpcds-config:/home/tpcds/.tpcds-util
    
    # Environment variables
    environment:
      - TPCDS_DB_PASSWORD=${TPCDS_DB_PASSWORD:-TestPassword123}
    
    # Keep container running for interactive use
    stdin_open: true
    tty: true
    
    # Default command shows help
    command: ["--help"]

volumes:
  tpcds-config:
    driver: local
  oracle-data:
    driver: local